error: mark NoActiveThreads as `deprecated`
This variant is no longer generated, so note that it will be removed.

Signed-off-by: Sean Cross <sean@xobs.io>